### ISSUE TITLE
Staging

### ISSUE THREAD

**Issue by Przecza** [gugcz/web21-frontend#1]
Vytvořit staging pro rychlou verifikaci non developery
Nasadit aktuální master

**Comment by ryzizub** [comment]
Published 🚀

**Comment by Przecza** [comment]
@ryzizub mám pocit, že větev staging je k ničemu. Že se na staging nasazuje main. Mě to nevadí. pro staging nepotřebuji samostatnou branch. pro produkci pak bude potřebovat.

**Comment by ryzizub** [comment]
😄  taky jsem si říkal, že je k ničemu. Smazat! 👍
